apiVersion: v1
data:
    admin-secret: ENC[AES256_GCM,data:ZROyMVm1A4tF/aljVLy/Ig==,iv:2boyufS+znVuRBL+4QLPgNj2W7smtsKrhYMKMy5iT6Y=,tag:g24TyWUZvBTRVNAF11xOGQ==,type:str]
    ceph-secret: ENC[AES256_GCM,data:apjY7Oz432f19d4wJROEWCSGiaSeaeGqpOqxKhQLHQSE+ozbNPnc2p69UFEagWfDiSfd89fK7uA=,iv:q7KgME6rWQyNYRwYbhQXsN/BiO6SGuNMKKVC9X3Smuw=,tag:ICq+yLUnO/WkgwoN8Aq8pw==,type:str]
    ceph-username: ENC[AES256_GCM,data:2BOHq/Gkup6Kn/TYqLlCj8afZ+IBl36KBgH+lg==,iv:tAQ86ykKSQnkfZC2sNBNGsS3dUWBFg6XylRmtRpdlx0=,tag:Gr03Pc/dur/Fy0XRByi3pA==,type:str]
    cluster-name: ENC[AES256_GCM,data:d0W/8c+b+vVH+MwV,iv:YooBi0oxwQqQN/fon+IOxRauGFkq7CPOskkX4oiWAFo=,tag:UjOPmQOdcLZdiPDiFE4X6w==,type:str]
    fsid: ENC[AES256_GCM,data:H6x2LVQuprYRydoz2oT4qpXxq77OcK5AROrYhGTKX6rhcIihFeR8emoATQFM6vmj,iv:QkcCDfNZtTUZ/h3tqAPNMkAyBeFXO5KR9wXxNZUvkzk=,tag:KmGn4oMfcUjz1QWggMJWpA==,type:str]
    mon-secret: ENC[AES256_GCM,data:GzQCOb4CgyNLiFczYK5dbg==,iv:tbE5aY1Q9FmgW5JZ+Q6na7U0gAohJ+gluB5Jx5l5EYM=,tag:FMkuXrmPREw2zwK4LdpTRA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rook-ceph-mon
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MU01NEVVa0JZQzRIRkNw
            eUtmMjI3aENodlNHYTNmUnNLQktKcHdmZ3pZCmdQL3RySkZVTGNydXdRK0h4Z2wr
            WmhyQ2F5L3YyMW56OFpwaVZLVEg2VWsKLS0tIEkzVGQ2MTgwZ0h3WklkT1dKV3hk
            RmtOR3RzMVlCRFlyWmxVTDAxUm5FdzQKrbHL8wlXsZcvBOEXxHFZATKGZhoNhuCh
            K99WSOQ6Qk34wFWBl8Rq2J0Yd/xoTB8y8MKztKWGSNDEYK+E1GiifA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T23:26:02Z"
    mac: ENC[AES256_GCM,data:vXU+99BCblxOy4UWqSdsvRNd5RdvVXTNgR6DwL2tsbdofagW+KrVUncO6prvZAq313gORoCD/1u5+UVIH1HB4BZjKUiiDktZqZoWE4AAtTgRS1AeYLBcNSuVsfxpQYp75UdtraqBn6xcM8pbde/P7qmTxgNbJM5KWCf+ByNtU7Q=,iv:i0+pzG0JsOPXvlKUaHCQRWo8kiuGmX6oYvFCDUVNXXY=,tag:cb0/efLGNx1jAwNrMivvbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
data:
    data: ENC[AES256_GCM,data:ChmpB1337rf+d9VHlXey0Piuhv/dmyPz1bM=,iv:2vtJRd16voobQufyXURM+2kv3Hipsx8wSvzwZhI4it0=,tag:YuD9JhLaPWXDb8XStVmTzA==,type:str]
    mapping: ENC[AES256_GCM,data:Ixs=,iv:u9ZFnhwgPJMWoCe0jXzXtTbZA8ffTOfQddm5pRuRP0w=,tag:BizQFcWsGtqLVu5Ac/lYfw==,type:str]
    maxMonId: ENC[AES256_GCM,data:fQ==,iv:cXIiaM5QiylkAt67r42ZsCLs0F5gihEBy3lq7wUzZ/4=,tag:ZMCPiwU/umTzFFW9ecbaBA==,type:str]
kind: ConfigMap
metadata:
    creationTimestamp: null
    name: rook-ceph-mon-endpoints
    namespace: rook-ceph
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MU01NEVVa0JZQzRIRkNw
            eUtmMjI3aENodlNHYTNmUnNLQktKcHdmZ3pZCmdQL3RySkZVTGNydXdRK0h4Z2wr
            WmhyQ2F5L3YyMW56OFpwaVZLVEg2VWsKLS0tIEkzVGQ2MTgwZ0h3WklkT1dKV3hk
            RmtOR3RzMVlCRFlyWmxVTDAxUm5FdzQKrbHL8wlXsZcvBOEXxHFZATKGZhoNhuCh
            K99WSOQ6Qk34wFWBl8Rq2J0Yd/xoTB8y8MKztKWGSNDEYK+E1GiifA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T23:26:02Z"
    mac: ENC[AES256_GCM,data:vXU+99BCblxOy4UWqSdsvRNd5RdvVXTNgR6DwL2tsbdofagW+KrVUncO6prvZAq313gORoCD/1u5+UVIH1HB4BZjKUiiDktZqZoWE4AAtTgRS1AeYLBcNSuVsfxpQYp75UdtraqBn6xcM8pbde/P7qmTxgNbJM5KWCf+ByNtU7Q=,iv:i0+pzG0JsOPXvlKUaHCQRWo8kiuGmX6oYvFCDUVNXXY=,tag:cb0/efLGNx1jAwNrMivvbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:1YwZwWZ3xgFenVT69ycYRQ==,iv:eN8dxPOXTWgQ4QIoAJ+jEqlFJBSKSWos0I8Iyg/kLjA=,tag:dm/+8ACDGPIdWoHp76fBVA==,type:str]
    userKey: ENC[AES256_GCM,data:CRR/fnWxRJRCmo+Llwe+EqnL23kApeX2dXqimpjxcVSuTcJT7ydDr08Qtp++Wl3crD7mUWs13VE=,iv:pFmHcLOCIFUf1uA6gEimjxSehnm65/l/VMtSj2gRtP8=,tag:TrfYIKOoheVYbwFAcoWU0Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rook-csi-rbd-node
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MU01NEVVa0JZQzRIRkNw
            eUtmMjI3aENodlNHYTNmUnNLQktKcHdmZ3pZCmdQL3RySkZVTGNydXdRK0h4Z2wr
            WmhyQ2F5L3YyMW56OFpwaVZLVEg2VWsKLS0tIEkzVGQ2MTgwZ0h3WklkT1dKV3hk
            RmtOR3RzMVlCRFlyWmxVTDAxUm5FdzQKrbHL8wlXsZcvBOEXxHFZATKGZhoNhuCh
            K99WSOQ6Qk34wFWBl8Rq2J0Yd/xoTB8y8MKztKWGSNDEYK+E1GiifA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T23:26:02Z"
    mac: ENC[AES256_GCM,data:vXU+99BCblxOy4UWqSdsvRNd5RdvVXTNgR6DwL2tsbdofagW+KrVUncO6prvZAq313gORoCD/1u5+UVIH1HB4BZjKUiiDktZqZoWE4AAtTgRS1AeYLBcNSuVsfxpQYp75UdtraqBn6xcM8pbde/P7qmTxgNbJM5KWCf+ByNtU7Q=,iv:i0+pzG0JsOPXvlKUaHCQRWo8kiuGmX6oYvFCDUVNXXY=,tag:cb0/efLGNx1jAwNrMivvbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
data:
    userID: ENC[AES256_GCM,data:SZI7pay2aSkn7XrPHQSvnKFqLtQjNF2IymfkHw==,iv:H31Ud0LDeZCij3LbE2lyArkoGTJm54+brWFYdOcF06o=,tag:V9TDDJSPiwzDkjY1UoaPpw==,type:str]
    userKey: ENC[AES256_GCM,data:P6YLNTco/7J3Rno9WdEpd/vIUkqtIkE+eR279+xBhqtDET937r44KI2mx+QskCtScNRamlTRvo8=,iv:2WT/3NuGElnO3B77xo2YYfi78EZrFNqNMux18lwPGVU=,tag:XC35ZIoGPLRFObLTWWZyzQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rook-csi-rbd-provisioner
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MU01NEVVa0JZQzRIRkNw
            eUtmMjI3aENodlNHYTNmUnNLQktKcHdmZ3pZCmdQL3RySkZVTGNydXdRK0h4Z2wr
            WmhyQ2F5L3YyMW56OFpwaVZLVEg2VWsKLS0tIEkzVGQ2MTgwZ0h3WklkT1dKV3hk
            RmtOR3RzMVlCRFlyWmxVTDAxUm5FdzQKrbHL8wlXsZcvBOEXxHFZATKGZhoNhuCh
            K99WSOQ6Qk34wFWBl8Rq2J0Yd/xoTB8y8MKztKWGSNDEYK+E1GiifA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T23:26:02Z"
    mac: ENC[AES256_GCM,data:vXU+99BCblxOy4UWqSdsvRNd5RdvVXTNgR6DwL2tsbdofagW+KrVUncO6prvZAq313gORoCD/1u5+UVIH1HB4BZjKUiiDktZqZoWE4AAtTgRS1AeYLBcNSuVsfxpQYp75UdtraqBn6xcM8pbde/P7qmTxgNbJM5KWCf+ByNtU7Q=,iv:i0+pzG0JsOPXvlKUaHCQRWo8kiuGmX6oYvFCDUVNXXY=,tag:cb0/efLGNx1jAwNrMivvbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
data:
    adminID: ENC[AES256_GCM,data:qBQgrXHTJ9s8YGd5+kKP0ySCl2Y=,iv:m3TAR7F40zWunNiDKEE+2tSeZq1eDaJQV+05ujSDYaA=,tag:sUSgwAjAvhS92HuSOEHfZQ==,type:str]
    adminKey: ENC[AES256_GCM,data:SuQrOPeBXVTKt9wdITEbshgDJZ27uBimersfkwOt3N9duEGa3S6791XkYNyWZwvG8sZz91xdDvA=,iv:q9XUYgP0pPtQ/zc4nFTICXwuBHfOyMaVyD1Gy8Z8YgE=,tag:h1w4GHPsUndCbuWiw3Gumg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rook-csi-cephfs-node
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MU01NEVVa0JZQzRIRkNw
            eUtmMjI3aENodlNHYTNmUnNLQktKcHdmZ3pZCmdQL3RySkZVTGNydXdRK0h4Z2wr
            WmhyQ2F5L3YyMW56OFpwaVZLVEg2VWsKLS0tIEkzVGQ2MTgwZ0h3WklkT1dKV3hk
            RmtOR3RzMVlCRFlyWmxVTDAxUm5FdzQKrbHL8wlXsZcvBOEXxHFZATKGZhoNhuCh
            K99WSOQ6Qk34wFWBl8Rq2J0Yd/xoTB8y8MKztKWGSNDEYK+E1GiifA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T23:26:02Z"
    mac: ENC[AES256_GCM,data:vXU+99BCblxOy4UWqSdsvRNd5RdvVXTNgR6DwL2tsbdofagW+KrVUncO6prvZAq313gORoCD/1u5+UVIH1HB4BZjKUiiDktZqZoWE4AAtTgRS1AeYLBcNSuVsfxpQYp75UdtraqBn6xcM8pbde/P7qmTxgNbJM5KWCf+ByNtU7Q=,iv:i0+pzG0JsOPXvlKUaHCQRWo8kiuGmX6oYvFCDUVNXXY=,tag:cb0/efLGNx1jAwNrMivvbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
data:
    adminID: ENC[AES256_GCM,data:0TAn/qN+5fj0Sutu+5Uo3zY24Z1/axO/TAvCJrb/mq0=,iv:rPRPk6r7PSbSasT6x4D0H2750vu7pnkIvAcHeTOAHAw=,tag:B5jMH3mlS/VUpOm+A73koA==,type:str]
    adminKey: ENC[AES256_GCM,data:0UsNz0ILjXQI8C33Fj6VDWY/UODflG1U/mnH7KwNRQHZRdsol9MdWQyIovSu9iK0UjFeFyzt2us=,iv:bTXqew+ZmTt9rl4kkG7UZ0mI1Dj1lccvPCkDWTZkdss=,tag:+G+8WRVT1/7S9yxt/EWzKA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: rook-csi-cephfs-provisioner
    namespace: rook-ceph
type: kubernetes.io/rook
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6MU01NEVVa0JZQzRIRkNw
            eUtmMjI3aENodlNHYTNmUnNLQktKcHdmZ3pZCmdQL3RySkZVTGNydXdRK0h4Z2wr
            WmhyQ2F5L3YyMW56OFpwaVZLVEg2VWsKLS0tIEkzVGQ2MTgwZ0h3WklkT1dKV3hk
            RmtOR3RzMVlCRFlyWmxVTDAxUm5FdzQKrbHL8wlXsZcvBOEXxHFZATKGZhoNhuCh
            K99WSOQ6Qk34wFWBl8Rq2J0Yd/xoTB8y8MKztKWGSNDEYK+E1GiifA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T23:26:02Z"
    mac: ENC[AES256_GCM,data:vXU+99BCblxOy4UWqSdsvRNd5RdvVXTNgR6DwL2tsbdofagW+KrVUncO6prvZAq313gORoCD/1u5+UVIH1HB4BZjKUiiDktZqZoWE4AAtTgRS1AeYLBcNSuVsfxpQYp75UdtraqBn6xcM8pbde/P7qmTxgNbJM5KWCf+ByNtU7Q=,iv:i0+pzG0JsOPXvlKUaHCQRWo8kiuGmX6oYvFCDUVNXXY=,tag:cb0/efLGNx1jAwNrMivvbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
