---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-config
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: csi-ceph-blockpool
  resources:
    requests:
      storage: 8Gi
