---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: a-random-name
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Mi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs
  volumeMode: Filesystem
