apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:7jZKL7zCIVWGOUMKjF0OCxc3yI9ILrrujoCz8uMm7pnvgx3T2i6cnQ==,iv:W6x/Ta9ntUHH+vUG4Dhf+3SRGdQspLSazQvzPe9a9DY=,tag:z0VVJ/M/+9ZXJucUSWei1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSmhBaFZyVTE5dzBtSzNy
            RnpHbW5RMTVaU1BwbW5PYTNrQlBaT1hscXkwCnpMUkY0NWVTZVFIdHR6TGNmMER5
            alRPOTJQZ1ZPNStvczhhNW43UHdEcDAKLS0tIDI2di9Wcmt0Y2hmalZZcW50M3lZ
            dERZM2w3UUp1YnJ3MHdWOWdkQ3lJRWMKQsg9PyP2aPa0P3kV290RCmcE0kh4kgNA
            +emsIXJOBsiaBghSjRqhKG7OhG/zuWrxX+pcXbpWZFJXwX5xu07udg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T16:37:52Z"
    mac: ENC[AES256_GCM,data:NDuhqHCBCldgYUTyPOscgmOredjK04M458PKJyJtdW5mnhcWyx47vyxLjU3FkdHH6GKS4gINlZbhwRm1sIlli/VW1VIHpXCFc3TYteM683BtqUfWhhlUaZ1K7txEpV3icqWC1M4iEsEM0CBiS2DdLh0ksW4sZ9JZKQY0UpQBGIQ=,iv:tW9j6hOs5wzHYSu+K63H9PexNVKTMnEDD4CX6rci4H8=,tag:+L8JFmeKZqp/9GVTGk6K/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
