---
kubernetes:
  children:
    master:
      hosts:
        k8s-0:
          ansible_host: 10.0.10.110
        k8s-1:
          ansible_host: 10.0.10.111
        k8s-2:
          ansible_host: 10.0.10.112
    worker:
      hosts:
        k8s-3:
          ansible_host: 10.0.10.113
        k8s-4:
          ansible_host: 10.0.10.114
        k8s-5:
          ansible_host: 10.0.10.115
