apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: default
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:hcXlVw==,iv:T3B2b8SeAFN4PYQSbdBXKl42IWD5m+7eUxKpQtYsQ7c=,tag:EIJIfE9YsORZXZPLMqYHcQ==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:7luKjFmLWjyIV8zZ,iv://V7EDxzcRcK/xOaxx8TZWsDkYtIq9G/4xpFDtwHltE=,tag:0mJblzW53YACVXagr/46lQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4REZSMHpmOU15d0g3REhL
            OHpoVkEwY1ovOVV6QTdkN1RoMkI0NVV5bnlVCjlGem9TaVBaWXdYS2FSYVhiYVBZ
            MlNnS200dWNmbG50V3NYT1hKaHRMVU0KLS0tIFh4engxRXgvUEk4M0lveTk5OXdz
            RHFPaDJCdWhGNGpVSy9STVVibmN0T1kK8sl5FCs7w3JYztYqCskr0o3zYC3LFAJO
            Cw0IbeXV7DToECLB/DVvVCAO0lpnheKGu7W9N0KcxBGXEdc9XKBZ9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-12T00:02:58Z"
    mac: ENC[AES256_GCM,data:RcWH3aI42eiHr9SFZn7xmiCRxmJpXoodP9Ada4307VPvIIzxmDOHvIQdk0rK5Xi6mkQVR9XTQ93O3R39XQuge4d+NfaIpmzl4qgX+YWZNgR4bIUNcuBXsp5YWIPPyf9iNrfmDby07gJLqCr5KNn1FuMipDYlxKS8YzS9B74LQoo=,iv:e/mv8pSuXWHtmv8ivzDsBoP1if0HMH8rAguYpDByCqk=,tag:Yzxqn7O166Dc6GFrmgywMg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
