---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: java-tf
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: minecraft
      version: 4.9.1
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: itzg/minecraft-server
      tag: latest@sha256:4d4a5c22c71708e7ae4f6152f7b06a1d920fd57d43c5ca135d2dc63f13765b2c
    minecraftServer:
      # EULA: https://account.mojang.com/documents/minecraft_eula
      eula: true
      # Minecraft version to install from https://papermc.io/downloads
      version: "1.18.2"
      # Type of server to run. Valid values are PAPER, SPIGOT, FORGE, FABRIC, VANILLA, BUKKIT, SPONGEVANILLA, SPONGE, MINECRAFT, WATERFALL, FLAMECORD
      type: "PAPER"
      # Download url for the server jar. Only required for CUSTOM type
      paperDownloadUrl: https://api.papermc.io/v2/projects/paper/versions/1.18.2/builds/388/downloads/paper-1.18.2-388.jar
      # Difficulty of the server. Valid values are peaceful, easy, normal, hard
      difficulty: normal
      # Maximum world size
      maxWorldSize: 10000
      # List of whitelisted players
      whitelist: AurumAutomaton,
                 Jinx_The_Crazy,
                 _jakewolf,
                 EbuVitae,
                 DaisyDuck1,
                 JayPKaye,
                 FluxCutie,
                 LegatusFlagrans,
                 ScarletCatto,
                 DawnTheDurr,
                 Taowosol,
                 Brandstellefter,
                 Not_Three_Foxes,
                 MarSparks,
                 CarameltehCat,
                 WarmCynder,
                 Cobalt_cat2,
                 Xkilljoy98,
                 Dryptosaurus,
                 VioletFurBean
      # URL for server icon
      icon: https://cdn.discordapp.com/attachments/1069418678556307456/1070330176312975470/Untitled_02-01-2023_06-42-57_3.png
      # List of operators
      ops: AurumAutomaton,Jinx_The_Crazy,Brandstellefter
      # Allow the nether
      allowNether: true
      # Whether to announce player achievements
      announcePlayerAchievements: false
      # Enable command blocks
      enableCommandBlock: true
      # Generate structures
      generateStructures: true
      # Whether to enable hardcore mode
      hardcore: false
      # Maximum build height
      maxBuildHeight: 256
      # Maximum tick time
      maxTickTime: 60000
      # View distance
      viewDistance: 10
      # Spawn protection radius
      spawnProtection: 16
      # Game mode. Valid values are survival, creative, adventure, spectator
      gameMode: survival
      serviceType: LoadBalancer
      servicePort: 62557
      LoadBalancerIP: 10.0.10.122
      rcon:
        enabled: true
        port: 25575
        existingSecret: rcon-password
        secretKey: rcon-password
        serviceType: ClusterIP
    persistence:
      storageClass: nfs
      dataDir:
        enabled: true
        size: 12Gi
    mcbackup:
      enabled: true
      backupInterval: 24h
      image:
        repository: itzg/mc-backup
        tag: latest@sha256:8f537a7b18f4039ec64dd5c16620478d200cd585e8cb7d391d8cdfc0e7a8bd3b
      storageClass: nfs
      persistence:
        backupDir:
          enabled: true
          Size: 1Gi
