---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: java-tf
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: minecraft
      version: 4.9.0
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: itzg/minecraft-server
      tag: latest@sha256:f955a1a4c99f0968fbb3cc8b8aa04fcaeab4ca068732587abd23f1426ea5a3f7
    minecraftServer:
      eula: true
      version: "1.18.2"
      type: "PAPER"
      paperDownloadUrl: https://api.papermc.io/v2/projects/paper/versions/1.18.2/builds/388/downloads/paper-1.18.2-388.jar
      difficulty: normal
      maxWorldSize: 10000
      whitelist: AurumAutomaton,Jinx_The_Crazy,_jakewolf,EbuVitae,DaisyDuck1,JayPKaye,FluxCutie,LegatusFlagrans,ScarletCatto,DawnTheDurr,Taowosol,Brandstellefter,Not_Three_Foxes,MarSparks,CarameltehCat,WarmCynder,Cobalt_cat2,Xkilljoy98,Dryptosaurus,VioletFurBean
      icon: https://cdn.discordapp.com/attachments/1069418678556307456/1070330176312975470/Untitled_02-01-2023_06-42-57_3.png
      ops: AurumAutomaton,Jinx_The_Crazy,Brandstellefter
      allowNether: true
      announcePlayerAchievements: false
      enableCommandBlock: true
      generateStructures: true
      hardcore: false
      maxBuildHeight: 256
      maxTickTime: 60000
      viewDistance: 10
      spawnProtection: 16
      gameMode: survival
      levelType: DEFAULT
      vanillaTweaksShareCodes: 9CIWkF,gquxh9
      onlineMode: true
      serviceType: LoadBalancer
      servicePort: 62557
      LoadBalancerIP: 10.0.10.122
      rcon:
        enabled: true
        port: 25575
        existingSecret: rcon-password
        secretKey: rcon-password
        serviceType: ClusterIP
    persistence:
      storageClass: nfs
      dataDir:
        enabled: true
        size: 12Gi
    mcbackup:
      enabled: true
      backupInterval: 24h
      image:
        repository: itzg/mc-backup
        tag: latest@sha256:74ac0d54c9a01312d6a8b271963c5b40998200b1f5b76ff49704ef2269aaede5
      storageClass: nfs
      persistence:
        backupDir:
          enabled: true
          Size: 1Gi
