apiVersion: v1
kind: Secret
metadata:
    name: minecraft-secret
    namespace: default
type: Opaque
stringData:
    minecraftServer:
        whitelist: ENC[AES256_GCM,data:r+KkR/gO9iIB9+Xda8waLTI5aLtUMCFl+cVq7coLfgjmjmJbJgNbqc8dPmNxHDVMTaIqCdya5is/j3UBEFsTdB+pL1GxJSFqlcggz7jHkYDsGhmnFbr3cyhF3gvNkNN0mBQbTQDVd1FaQVMLkb6pD+tqLOTHUo/mOdWFPoBo9OsPTuMWV/KoYeh5QqnNT0O69+PG5ZGsabDCLwVD4/HZ1/BYdXoDuD1ImmdEc3KaoZVv86U/De4JSrGjYCrudC7WHhyzobPeulioTpyJ/3okmz3rHQDP/2QPukMnrn2tFeU2kkH9nFYNx9KjKo+7MfGqdCg6RBNpVOXUI48=,iv:lVxuh9dFl0cG94nP/xP7VTdNmZDED6mFh3VVEAxjNZg=,tag:fTlDj4YnScRQZy98e/6UFw==,type:str]
        icon: ENC[AES256_GCM,data:I0O2IJDMjY+LcNoHi+TIi0j7TGEgPacLvpNXR9L7ijgge6xrCiL2gWmlUHY7JmfQ23qZONUOr8dxHFTSX1biDaDLJYSSF7iE1NUShHLnJ+dV1g+5WueUUoSQLeOD1vyvvPTc6G9rJpEG9yL2+759GEQ=,iv:1GAuAgWhNr6HpOU2XMSCF5oYkk4UjlWyDGDocIuwAGo=,tag:Ymc9KWcEeOS/7rvECSe5qg==,type:str]
        ops: ENC[AES256_GCM,data:tH8Jutkx2iruA66C62B0ZaUQgGccGup4UFPzINfozxhSbPh5M3YVax5SoMLF,iv:Y2NWr/33rT8XqhMwssvQd0aL1GuTHpyRMnPUOx3gIqE=,tag:tA0HkhzM8vjMk7aSkMyDWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cGtGWENLMVBoMm91K2pq
            UjVoK1NJTXdSYzhQUW5Bdm5FZUw2L3EwWER3CjlPRnR6bXI3VlFuYjBxSW5iNWQz
            bER4VmgxOVAzWGgvTEovTjZLTjlQZEkKLS0tIFNkY1pJb1JKdG9ScnNTbkQ2ZUwy
            KzZGdjE4L1FwYlJidk16VXNBcFNlWkUKWRSZYYS27419L6KvvXil9GHx1LuPhXIS
            yAXwrtVhLlWrCVCquUu1kqBOSd3VP/mcRFPxD6Unz9xspUJ6a+vPqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-18T22:09:05Z"
    mac: ENC[AES256_GCM,data:GLb6YSWRnY9gTeeXJWWi4TqluSWNuEv8vHC5S6W7rbaT24+zaXDRoFgrSU3SuwBqO+xf0UzrPQXU/799zGLbfjZXgH0GHU0O4+QyE3jLyFe2Rz/OK0famZbtByytImSRPaEJeusSNrqzCI93gxePCJRgQ2LZ6bIh0l9ohzIR+oM=,iv:XuPiVp7C/iRNJ9wawW3mOBe3GSgI4SMDQsda3VJYqdA=,tag:JyuczeINFXIYPfn1LuDszQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
metadata:
    name: rcon-password
    namespace: default
type: Opaque
stringData:
    rcon-password: ENC[AES256_GCM,data:fXQlwQcUzKS4do/B,iv:Vfs8efTmZt315a11E8NXhqqATsiIF4RB89yuTk8RCtc=,tag:Vdq8CT1J+p2vECECXjy/Mg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cGtGWENLMVBoMm91K2pq
            UjVoK1NJTXdSYzhQUW5Bdm5FZUw2L3EwWER3CjlPRnR6bXI3VlFuYjBxSW5iNWQz
            bER4VmgxOVAzWGgvTEovTjZLTjlQZEkKLS0tIFNkY1pJb1JKdG9ScnNTbkQ2ZUwy
            KzZGdjE4L1FwYlJidk16VXNBcFNlWkUKWRSZYYS27419L6KvvXil9GHx1LuPhXIS
            yAXwrtVhLlWrCVCquUu1kqBOSd3VP/mcRFPxD6Unz9xspUJ6a+vPqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-18T22:09:05Z"
    mac: ENC[AES256_GCM,data:GLb6YSWRnY9gTeeXJWWi4TqluSWNuEv8vHC5S6W7rbaT24+zaXDRoFgrSU3SuwBqO+xf0UzrPQXU/799zGLbfjZXgH0GHU0O4+QyE3jLyFe2Rz/OK0famZbtByytImSRPaEJeusSNrqzCI93gxePCJRgQ2LZ6bIh0l9ohzIR+oM=,iv:XuPiVp7C/iRNJ9wawW3mOBe3GSgI4SMDQsda3VJYqdA=,tag:JyuczeINFXIYPfn1LuDszQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
