apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:XgTcLqeMZqFsDJQZDET/ArKlVsrVLVKn1Jaa2lpi2EY7NeiwfQ==,iv:CaNfhzexEPraqJ/PI4bq0XFQnY9GKndnSY6rSPaLLRk=,tag:MpcF7oEqKLY8ibZzLfYgHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTXFYMnVmbkNkRmZtWVh0
            cHFtNG1DY3pIRVpMb3NuQW5CVUtoNWVmL2hBCjN0anBabmo0VXBudlpnbStDUWtR
            VHU3bGw0QVpqZStaQ1VHSmxUQ1dBa00KLS0tIFl5UFZnb1pSVWthd0NDMG94dXFt
            NFBISldsZEFtSlh3NTJzWnFzTEFvU0kKMMiqaC4ol7meWJ9GVLY1QXFLBnux3shP
            fRiM78xk9UiFWulMrW3iTZ0tMdx8DM+gkXPbCGhESY26soepRlk4tw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-10T16:37:51Z"
    mac: ENC[AES256_GCM,data:5+4LLko3nOcYnQujwSTxrueJZomb+baUg8X5BNAMZ6s00YaeWB0aWRzFOfdD/f8cD7b3gAtiJ9DlIVAaEcEFcgf9F1nAJ9x94+uwSBegPib33IUjpdPtUwX4zIGXRNAb9N/B5cHOZOQvYDgpthLpGf4Vjnho1wtQWALIMBx5LyY=,iv:wRoIhFTzv2kT12h3LGh1wXYiwg7haj5FEn6jvOnU3YI=,tag:HsjBxEBB4HnBPK6RQZddGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
