apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:DLpFmg8wjEg8Mn85B5pNs/BuvbVwjjwt,iv:ZJEgPsVHEqRDGJTGmQgMo05OHlw13aHpyPrfJqr0dLw=,tag:l/2Bu0W2lE1Lttua9qEALw==,type:str]
    api-key: ENC[AES256_GCM,data:Wlf/fUqTk9RWAwG/hOnQM3bgJE+33y25F7bh9DGqSvdTX3jmhA==,iv:Rjfqd2qbSzQreppu9EYn7NNIAg4/UNHA+bATmhx82sg=,tag:ojk+zjDomzQub+YdVXeJeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdHI3MkpLa3B1VHUyemkv
            YTRtKy84RHBLMnhzd1RtZ21FVUdkU0wrRGhVCjMwV3FFYTJ4OWxIaXZyR3dZeld2
            Qkl2MmxIbmVTVXBsME1mTTNvaHV4bzAKLS0tIDNCdURza1owdEphNkRMR256ajFO
            cElHaE1ibWVwOWZZbGdHY05KYitXYjQKEJrVJst/rBVI1ioqT5b269rqjvYBWcY9
            nrNTPjIdOarZf2dltr5ChjX4nhNS0iojJkeVxldY1uACftaWHOrgpw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-30T21:10:10Z"
    mac: ENC[AES256_GCM,data:tU7LRwZ3d51SBVpfJ2SPtf8/cNrfCFB5hVBagn7rQFi8UahH8OCpGatoL6vo8yxrVWZnnjRZ+gtSw0n1Pf4ixYR8QNld7oVNqlvHIqlFOGzhg7DdGHGxQ6eQa5iblbeJhn6IJmZ/y66aVyHsiHYByeSo3YqtKdxG0/TV/HYAxcQ=,iv:Cx3gGYTyfNhVAq4pO4LEcelE9/UPre8JNHKnZdlYcwM=,tag:hYEE2ENJiEqXXeuimahOOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
