---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./echo-server/ks.yaml
  - ./hajimari/ks.yaml
  - ./minio/ks.yaml
  - ./sonarr/ks.yaml
  - ./radarr/ks.yaml
  - ./bazarr/ks.yaml
  - ./prowlarr/ks.yaml
  - ./minecraft/ks.yaml
  - ./tdarr/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./jellyfin/ks.yaml
  # - ./minecraft-maxine/ks.yaml
  #some-comment-here
