---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      # -- image repository
      repository: ghcr.io/onedr0p/radarr-develop
      # @default -- chart.appVersion
      tag: 4.6.4.7568@sha256:7dd197028efcc9e4e4bc52cd383efbaa1b6631c8932b3f831a3a1b1687fa8954
      # -- image pull policy
      pullPolicy: IfNotPresent
    env:
      TZ: America/Chicago
      RADARR__INSTANCE_NAME: Radarr
    envFrom:
      - secretRef:
          name: radarr-secret
    service:
      main:
        enabled: true
        ports:
          http:
            port: &radarr-port 7878
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          hajimari.io/icon: mdi:television-classic
        hosts:
          - host: &radarr-host "radarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *radarr-port
        tls:
          - hosts:
              - *radarr-host
    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          exec:
            command:
              - /usr/bin/env
              - bash
              - -c
              - curl --fail localhost:7878/api/v3/system/status?apiKey=`IFS=\> && while
                read -d \< E C; do if [[ $E = "ApiKey" ]]; then echo $C; fi; done < /config/config.xml`
          failureThreshold: 10
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 30
    persistence:
      config:
        enabled: true
        existingClaim: radarr-config
        retain: true
      movies:
        enabled: true
        mountPath: /movies
        existingClaim: radarr-movies
        retain: true
      downloads:
        enabled: true
        mountPath: /downloads-usenet
        existingClaim: sabnzbd-downloads
        retain: true
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch
      supplementalGroups: [10000]
    resources:
      requests:
        cpu: 10m
        memory: 250Mi
      limits:
        memory: 2000Mi
