---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: java-maxine
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: minecraft
      version: 4.8.0
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    timeout: 11m
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    timeout: 11m
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: docker.io/itzg/rcon
      tag: latest@sha256:a9fc0b4116a7034c4849a4160d139a589bbf9211df64b48cc404e74c3e7bb730
    service:
      type: ClusterIP
      httpPort: 80
      wsPort: 4327
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        hajimari.io/icon: mdi:cube-scan
      host: &rcon-host rcon-maxine.aurumautomaton.com
      path: /
      pathType: ImplementationSpecific
      tls:
        - hosts:
            - *rcon-host
    rconWeb:
      isAdmin: true
      passwordExistingSecret: rcon-password
      passwordKey: rcon-password
      game: minecraft
      rconHost: java-maxine-minecraft-rcon
      rconPort: 62557
      rconPasswordExistingSecret: rcon-password
      rconPasswordKey: rcon-password
