---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: java-maxine
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: minecraft
      version: 4.9.1
      sourceRef:
        kind: HelmRepository
        name: itzg
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    timeout: 11m
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    timeout: 11m
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controller:
      annotations:
        reloader.stakater.com/auto: "true"
    image:
      repository: itzg/minecraft-server
      tag: latest@sha256:2b4f1c3cd475daa1f768d316e32b206cce0855ccc11ae39924b3fdeedb85621a
    resources:
      requests:
        memory: 8Gi
        cpu: 1000m
    livenessProbe:
      command:
        - mc-health
      initialDelaySeconds: 540
      periodSeconds: 5
      failureThreshold: 30
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      command:
        - mc-health
      initialDelaySeconds: 540
      periodSeconds: 5
      failureThreshold: 30
      successThreshold: 1
      timeoutSeconds: 1
    startupProbe:
      command:
        - mc-health
      enabled: false
      failureThreshold: 120
      periodSeconds: 10
    minecraftServer:
      eula: true
      version: "1.18.2"
      type: "FORGE"
      forgeVersion: 40.2.1
      # downloadModpackUrl: https://www.curseforge.com/api/v1/mods/711537/files/4558204/download
      # cfServerMod: https://www.curseforge.com/api/v1/mods/711537/files/4558204/download
      difficulty: hard
      maxWorldSize: 5000
      whitelist: AurumAutomaton,OmniSnuggle,MaxTheMooshroom,SkyeMeows,Okuumu,melanomar,jkleinveld,greytux,KennyTheLogician,Krivy
      icon: https://vaulthunters.gg/assets/vh-logo-lg-a4fbcbdd.png
      motd: "Welcome to VaultHunters gaymers! Powered by Serpie's Service Stack."
      ops: AurumAutomaton,MaxTheMooshroom
      allowNether: true
      announcePlayerAchievements: true
      enableCommandBlock: true
      generateStructures: true
      hardcore: false
      levelSeed: -9115858110306877132
      maxBuildHeight: 320
      maxTickTime: 60000000
      viewDistance: 10
      spawnProtection: 0
      gameMode: survival
      levelType: DEFAULT
      memory: 6000M
      jvmOpts: ""
      jvmXXOpts: "-XX:+UseG1GC -Dsun.rmi.dgc.server.gcInterval=2147483646 -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M"
      onlineMode: true
      serviceType: LoadBalancer
      servicePort: 62558
      LoadBalancerIP: 10.0.10.124
      rcon:
        enabled: true
        port: 25575
        existingSecret: rcon-password
        secretKey: rcon-password
        serviceType: ClusterIP
    persistence:
      storageClass: csi-ceph-blockpool
      dataDir:
        enabled: true
        Size: 45Gi
    mcbackup:
      enabled: true
      image:
        repository: itzg/mc-backup
        tag: latest@sha256:8f537a7b18f4039ec64dd5c16620478d200cd585e8cb7d391d8cdfc0e7a8bd3b
      storageClass: nfs
      persistence:
        backupDir:
          enabled: true
          Size: 300Gi
