apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:cOV0oT5l5I7XEFDDDcIwUqLV,iv:bC1ozEr7VDlVswbqPNS32piPLrAP0ERTpVeGSsvNxh0=,tag:0ySEBaJbU/pEch8w7GBsOA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:R4d47Ftk/chh4nlCEZI5GV7jLpvdQJzY,iv:7sngKU+KSePWpaVinWlNM/s/fOIrMJnPydFchu+Kwp0=,tag:nW9ZTNixCGvOc5MIGU3dWQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:RPBSp1svSh5JpqJh4fA+pWWDd9wWgVEAu4OmOGTIntnS/97a,iv:YFBv7xkMUpIFv+163tPfLlpdoIZYhYP46ydQualO6MY=,tag:/OEyKKBJhVf010nAE13hHw==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:im9l5xntkah+HEfjEPil40zF/aTuSRYqGh9+Blw+nEyyulK29qrXnXm/HFAVKZXDrlc=,iv:oLML4jGGuYaITxCXEq/6fcpVV72yxuhjrDupBevd2AY=,tag:wlYQAavNZGnFU/J2GGcJQA==,type:str]
    AUTHENTIK_EMAIL_USERNAME: ENC[AES256_GCM,data:zLnh9Amg4zuiFrCt5uI5sA1Ly7FUcnejpe/l4h2jOhY2kw==,iv:CwgJE+sJ5MHy3j5GTmS7GwPwE7LRWmo74erMIRnPY1M=,tag:wHVWa2zm8sywlZH8SYayWA==,type:str]
    AUTHENTIK_EMAIL_PASSWORD: ENC[AES256_GCM,data:Oj7HQn2g6iXZB3CkO50PraRE7frB8p7l6Wtw3u4qRMedVZtdRsNcZ/NtlSFJ2IDqfOE=,iv:aPSP/wMfcMgCuKm8CJXqPgz70DYUQ5Hr8tjRv73xTzg=,tag:PduM2tqwwdslShmp/qnx6Q==,type:str]
    AUTHENTIK_POSTGRESQL_PASSWORD: ENC[AES256_GCM,data:xdXuRhohh7GsTUgbLYG/119UuC6zwDXVN8Tj3ayEpCPhTYsCopE6QyGh9eKvrCNkh1c=,iv:BrjRApsaxnPrgu5CpQalx62/Im52q++TCY7DMkTAZOk=,tag:bUjaLCXS3H16huRtLznL/w==,type:str]
    AUTHENTIK_REDIS_PASSWORD: ENC[AES256_GCM,data:xjudwFBS5/5AY/FZtpVuWakgGH3iWxbhorkBpZhSwq7OHnGsEJ+C,iv:TD1WvVt6umaBQUSkokupwznqCPl6Oh+n1GND00GeUtE=,tag:D774uIqPusBZnsJXLG/ZDA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1m9rudmsxsqsurxhkmx2j8r9a0m3fxf27v5jlns2c2cjajnr4cq7qtl3fne
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTWs1L08xbm9XMjFiT1Nv
            RDZreWR4UFZOcXpvamRsbjAzSGg0eHUrbkU0CnZkZ1BSVmpneFloWmlHWEIzeHR1
            ZVBLajJiSG1jOVljZ1RxZUJ3QXJFR1UKLS0tIHNrYW5OdFdTNENRRy9WYzloc1A1
            WEdTTnVHQzJiYUlrOGtsVitzMXZVaDgKlOPV0R/GuoXHcFyx4DaORWKswukwAZuI
            Ci7bOPFfigxrWliQvUcHu8cRiUF+GZD2lfxLQIPc362cOagXEEixww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-30T22:13:17Z"
    mac: ENC[AES256_GCM,data:w7boeeuYG2kjs3IREtJka2H5bTNajNiLHqDbMJEqmcGG47IpCiCzAZWiqryl85Jn2ThZuWnVx5pqs2c5Vl8cmhTcqqupBWDvxeiI+wBGOTyM8k1JKUPHzhnRLnCdp7kSuzC+E42FknusOdN3m7uOwORgdS7iGqyFDyi3N5xhAAQ=,iv:fJaQlWv5vskbWvhfQJnOeDZrJkejESYYSV6DLZFhsx0=,tag:U6jlB79KDv9RZvm6CUr91w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
