---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Chicago"
  KUBE_VIP_ADDR: "10.0.10.118"
  METALLB_LB_RANGE: "10.0.10.120-10.0.10.130"
  METALLB_K8S_GATEWAY_ADDR: "10.0.10.121"
  METALLB_INGRESS_ADDR: "10.0.10.120"
